const questions = [
  "Gotten free food on the Oval?",
  "Talked to a stranger on High Street?",
  "Skipped a class all semester?",
  "Failed an exam?",
  "Slept through an exam?",
  "Pulled an all-nighter in Thompson?",
  "Used ChatGPT for an entire assignment?",
  "Posted on your graduating class's Facebook page?",
  "Had a pet in the dorms?",
  "Drank in the dorms?",
  "Gotten pierced/tattooed in the dorms",
  "Drank underage?",
  "Blacked out?",
  "Been hungover during an exam?",
  "Been drunk during an exam?",
  "Cheated on homework?",
  "Cheated on a test?",
  "Lied to a professor to get out of an exam?",
  "Been on academic probation?",
  "Had a COAM case?",
  "Gotten locked out of your dorm/apartment?",
  "Been to a non-football OSU sporting event?",
  "Heard John White Noise?",
  "Gotten a Chitt Show?",
  "Been to Beat the Clock?",
  "Been to Midway Madness?",
  "Been to Bulls/Uno?",
  "Been to an away football game?",
  "Been to the RPAC sauna?",
  "Jumped in Mirror Lake?",
  "Ran a two-man?",
  "Snuck into the Shoe?",
  "Set off a fire alarm in a dorm room?",
  "Got shower mold?",
  "Stolen someone's Grubhub food",
  "Had your Grubhub food stolen?",
  "Smoked a cigarette outside a bar?",
  "Smoked in the dorms?",
  "Smoked weed in the Oval?",
  "Snuck into a bar?",
  "Snuck into the dining hall?",
  "Had a fake ID?",
  "Went to dining hall drunk?",
  "Taken a scooter drunk?",
  "Gotten kicked out of a bar?",
  "Gotten kicked out of a party?",
  "Blocked too hard and didn't make it to a game?",
  "Been to a block you weren't invited to?",
  "Rushed a fraternity/sorority?",
  "Stolen something from a classroom?",
  "Masturbated in a communal bathroom?",
  "Masturbated on campus?",
  "Had sex in the dorms?",
  "Had sex on campus?",
  "Had sex at a party?",
  "Sexiled a roommate?",
  "Been sexiled?",
  "Hooked up with a Brutus?",
  "Kissed someone the night you met them?",
  "Hooked up with someone the night you met them?",
  "Had a one-night stand?",
  "Dated an OSU student in college?",
  "Dated an non-OSU student in college?",
  "Dated/slept with a TA?",
  "Dated/slept with an RA?",
  "Dated/slept with a professor?",
  "Slept with someone more than 5 years older than you?",
  "Slept with a parent on parent's weekend?",
  "?",
  "Spent a night at a frat/sorority house?",
  "Done any drugs harder than weed?",
  "Had your stomach pumped/hospital from drinking?",
  "Flipped a car?",
  "Thrown up in a Lyft?",
  "Gotten alcohol poisoning?",
  "Drank before noon on a weekday?",
  "Snuck alcohol into the Shoe?",
  "Cheated or been cheated on?",
  "Had a threesome?",
  "Sent nudes?",
  "Asked for nudes?",
  "Driven high/drunk?",
  "Gotten a DUI?",
  "Been questioned by OSU police?",
  "Been questioned by Columbus police?",
  "Been arrested?",
  "Kissed more than one person in the same day?",
  "Had sex with more than one person in the same day?",
  "Kissed someone of the same sex?",
  "Had sex with someone of the same sex?",
  "Used someone else's fake ID?",
  "Gotten a fake ID taken away?",
  "Pregancy scare?",
  "Had sex without protection?",
  "Done a walk of shame?",
  "Gotten an STD?",
  "Streaked the field?",
  "Paid or been paid for sex?",
  "Filmed or been filmed sexually?",
  "Graduated?",
];

while (questions.length < 100) {
  questions.push(`Question ${questions.length + 1}?`);
}

export default questions;
